### ISSUE TITLE
Crash in worlds with large amount of video players

### ISSUE THREAD

**Issue by yoshiyoshyosh** [Frozenreflex/NeosVideoPlayerFix#3]
Distro: Void Linux
libvlc version: 3.0.17.4_4

In worlds with a large amount of video players (currently only tested with 8 and more video players, but it may come in earlier), this mod will cause the game to crash. Removing the mod does not crash the game in the exact same situation.
There are no important logs related to this in the normal Neos log, but there is a stacktrace in the `Player.log`:

```
[00007f7ac417e620] adaptive demux: Changing stream format Unknown -> MP4
munmap_chunk(): invalid pointer
Caught fatal signal - signo:6 code:-6 errno:0 addr:0x3e800000816
Obtained 31 stack frames.
#0  0x007f7cc7fef900 in funlockfile
#1  0x007f7cc5b31f81 in gsignal
#2  0x007f7cc5b1b536 in abort
#3  0x007f7cc5b734f8 in __libc_message
#4  0x007f7cc5b7af3a in malloc_printerr
#5  0x007f7cc5b7b38c in munmap_chunk
#6  0x007f7b9e29d6ce in std::pair<std::_Rb_tree_iterator<std::pair<unsigned long const, float> >, bool> std::_Rb_tree<unsigned long, std::pair<unsigned long const, float>, std::_Select1st<std::pair<unsigned long const, float> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, float> > >::_M_emplace_unique<std::pair<unsigned long, float> >(std::pair<unsigned long, float>&&)
#7  0x007f7b9e299dff in std::pair<std::_Rb_tree_iterator<std::pair<unsigned long const, float> >, bool> std::_Rb_tree<unsigned long, std::pair<unsigned long const, float>, std::_Select1st<std::pair<unsigned long const, float> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, float> > >::_M_emplace_unique<std::pair<unsigned long, float> >(std::pair<unsigned long, float>&&)
#8  0x007f7b9e299fb9 in std::pair<std::_Rb_tree_iterator<std::pair<unsigned long const, float> >, bool> std::_Rb_tree<unsigned long, std::pair<unsigned long const, float>, std::_Select1st<std::pair<unsigned long const, float> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, float> > >::_M_emplace_unique<std::pair<unsigned long, float> >(std::pair<unsigned long, float>&&)
#9  0x007f7b9e2899e3 in std::__cxx11::_List_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_clear()
#10 0x007f7b9e299d2c in std::pair<std::_Rb_tree_iterator<std::pair<unsigned long const, float> >, bool> std::_Rb_tree<unsigned long, std::pair<unsigned long const, float>, std::_Select1st<std::pair<unsigned long const, float> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, float> > >::_M_emplace_unique<std::pair<unsigned long, float> >(std::pair<unsigned long, float>&&)
#11 0x007f7b9e2ac663 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#12 0x007f7b9e2a434e in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#13 0x007f7b9e2a44c4 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#14 0x007f7b9e2a4536 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#15 0x007f7c080d5cec in vlc_stream_Peek
#16 0x007f7b9e63f3ab in (Unknown)
#17 0x007f7c0809659a in vlc_ureduce
#18 0x007f7c08096b44 in vlc_module_load
#19 0x007f7c080bb157 in input_DecoderFlush
#20 0x007f7c080bb2ea in demux_New
#21 0x007f7b9e2a1777 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#22 0x007f7b9e2ae565 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#23 0x007f7b9e2ae662 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#24 0x007f7b9e2ade31 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#25 0x007f7b9e2ae09d in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#26 0x007f7b9e2a84b3 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#27 0x007f7b9e2a885b in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#28 0x007f7b9e2a8989 in std::pair<std::_Rb_tree_iterator<void const*>, bool> std::_Rb_tree<void const*, void const*, std::_Identity<void const*>, std::less<void const*>, std::allocator<void const*> >::_M_insert_unique<void const* const&>(void const* const&)
#29 0x007f7cc7fe4eae in start_thread
#30 0x007f7cc5bf32ff in clone
```

**Comment by Frozenreflex** [comment]
All this mod does is switch two strings to make the game properly load the provided binaries for libvlc and local binaries for youtubedl(p), so this is likely caused by the libvlc binary provided in the game, and I have no idea how to fix it other than maybe switching it out for a newer binary.
